services:
  - type: web
    name: quiz-app-backend
    runtime: node
    rootDir: NowaAplikacja/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: static
    name: quiz-app-frontend
    rootDir: NowaAplikacja/dist
    buildCommand: cd NowaAplikacja && npm install && npm run build
    publishPath: ./
