services:
  - type: web
    name: quiz-app-backend
    runtime: node
    rootDir: NowaAplikacja/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: quiz-app-frontend
    runtime: node
    rootDir: NowaAplikacja
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
